import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { ActionButton, Card, CompanyIcon, CompanyPage, companyColors as c, PageScroll, Tag } from '@/components/company/company-ui';
import { companyJobs } from '@/components/company/company-data';

const PillSelect = ({ values, value, onChange }: { values: string[]; value: string; onChange: (value: string) => void }) => <View style={s.pills}>{values.map((item) => <Pressable key={item} onPress={() => onChange(item)} style={[s.pill, value === item && s.pillActive]}><Text style={[s.pillText, value === item && s.pillTextActive]}>{item}</Text></Pressable>)}</View>;

function Field({ label, value, onChangeText, placeholder, multiline = false }: { label: string; value: string; onChangeText: (value: string) => void; placeholder?: string; multiline?: boolean }) {
  return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={c.muted} multiline={multiline} textAlignVertical={multiline ? 'top' : 'center'} style={[s.input, multiline && s.textarea]} /></View>;
}

export default function CompanyCreateJob() {
  const [title, setTitle] = useState('Thực tập sinh Backend Node.js');
  const [department, setDepartment] = useState('Sản phẩm & Kỹ thuật');
  const [deadline, setDeadline] = useState('30/10/2026');
  const [workMode, setWorkMode] = useState('Kết hợp');
  const [location, setLocation] = useState('TP. Hồ Chí Minh');
  const [salary, setSalary] = useState('4.000.000');
  const [salaryMax, setSalaryMax] = useState('6.000.000');
  const [description, setDescription] = useState('Cùng xây dựng hệ thống cho sản phẩm số. Bạn sẽ tham gia vào quá trình phát triển, thiết kế API và phối hợp cùng nhóm Frontend.');
  const [skills, setSkills] = useState(['JavaScript', 'Node.js', 'Git']);
  const [extraSkill, setExtraSkill] = useState('');

  const addSkill = () => {
    const next = extraSkill.trim();
    if (!next || skills.includes(next)) return;
    setSkills((current) => [...current, next]);
    setExtraSkill('');
  };
  const saveJob = (status: 'Bản nháp' | 'Đã đăng') => {
    if (!title.trim()) { Alert.alert('Thiếu tiêu đề', 'Nhập tiêu đề bài tuyển dụng trước khi lưu.'); return; }
    companyJobs.unshift({ id: `job-${Date.now()}`, title: title.trim(), department: department.trim() || 'Chưa phân bộ phận', workplace: workMode, location, deadline, applicants: 0, status, updated: 'Hôm nay', salary: `${salary} đ/tháng` });
    router.replace('/(company)/jobs');
  };

  return <CompanyPage><PageScroll>
    <View style={s.nav}><Pressable onPress={() => router.back()} style={s.back}><CompanyIcon name={{ ios: 'arrow.left', android: 'arrow_back', web: 'arrow_back' }} color={c.ink} /></Pressable><View style={{ flex: 1 }}><Text style={s.navTitle}>Tạo bài đăng tuyển dụng</Text><Text style={s.navSub}>Nexora Studio</Text></View><View style={s.avatar}><Text style={s.avatarText}>N</Text></View></View>
    <Card style={s.jobPreview}><View style={s.previewTop}><View style={s.logo}><Text style={s.logoText}>N</Text></View><View style={{ flex: 1 }}><Text style={s.company}>Nexora Studio</Text><Text style={s.helper}>TP. Hồ Chí Minh</Text></View></View><Text style={s.previewTitle}>{title || 'Tiêu đề vị trí'}</Text><Text style={s.previewSub}>{department || 'Bộ phận'}</Text><View style={s.pills}><Tag tone="purple">{workMode}</Tag><Tag tone="purple">Ứng dụng web</Tag></View><View style={s.separator} /><View style={s.previewDetail}><CompanyIcon name={{ ios: 'banknote', android: 'payments', web: 'payments' }} size={14} /><Text style={s.helper}>4–6 triệu đ / tháng</Text></View><View style={s.previewDetail}><CompanyIcon name={{ ios: 'calendar', android: 'calendar_month', web: 'calendar_month' }} size={14} /><Text style={s.helper}>Ứng tuyển đến {deadline}</Text></View><View style={s.pills}><Tag tone="gray">JavaScript</Tag><Tag tone="gray">Node.js</Tag><Tag tone="gray">Git</Tag></View><Text style={s.helper}>Mentor đồng hành · Hỗ trợ thực tập</Text></Card>
    <Card><Text style={s.sectionTitle}>Thông tin công việc</Text><Text style={s.sectionSub}>Dấu * là thông tin bắt buộc</Text><Field label="Tiêu đề bài đăng *" value={title} onChangeText={setTitle} placeholder="Ví dụ: Thực tập sinh Backend" /><Field label="Bộ phận · không bắt buộc" value={department} onChangeText={setDepartment} placeholder="Sản phẩm & Kỹ thuật" /><Field label="Hạn ứng tuyển *" value={deadline} onChangeText={setDeadline} placeholder="dd/mm/yyyy" /><Text style={s.label}>Hình thức làm việc *</Text><PillSelect values={['Tại văn phòng', 'Kết hợp', 'Từ xa']} value={workMode} onChange={setWorkMode} /><Field label="Địa điểm *" value={location} onChangeText={setLocation} placeholder="TP. Hồ Chí Minh" /><Text style={s.helper}>Văn phòng Nexora Studio · 24 Nguyễn Bỉnh Khiêm, phường Sài Gòn</Text><View style={s.salaryRow}><View style={{ flex: 1 }}><Field label="Lương tối thiểu · VND/tháng" value={salary} onChangeText={setSalary} placeholder="4.000.000" /></View><View style={{ flex: 1 }}><Field label="Lương tối đa · VND/tháng" value={salaryMax} onChangeText={setSalaryMax} placeholder="6.000.000" /></View></View><Text style={s.helper}>Lương thỏa thuận · Có thể để trống cả hai mức lương.</Text></Card>
    <Card><Text style={s.sectionTitle}>Mô tả công việc</Text><Text style={s.label}>Nội dung *</Text><Field label="" value={description} onChangeText={setDescription} multiline placeholder="Mô tả trách nhiệm, môi trường làm việc và quyền lợi..." /><Text style={s.helper}>Mô tả rõ vai trò, hướng dẫn và sản phẩm giúp ứng viên hiểu cơ hội.</Text></Card>
    <Card><Text style={s.sectionTitle}>Yêu cầu</Text><Text style={s.label}>Kỹ năng bắt buộc</Text>{['JavaScript và Node.js với nền tảng lập trình vững chắc', 'Thiết kế REST API và hiểu biết giao thức HTTP cơ bản', 'Cơ sở dữ liệu quan hệ (PostgreSQL hoặc tương đương)'].map((x) => <Text style={s.bullet} key={x}>•  {x}</Text>)}<View style={s.addSkillRow}><TextInput style={[s.input, { flex: 1 }]} value={extraSkill} onChangeText={setExtraSkill} placeholder="Thêm kỹ năng bắt buộc" placeholderTextColor={c.muted} /><Pressable onPress={addSkill}><Text style={s.purpleText}>+ Thêm</Text></Pressable></View><Text style={[s.label, { marginTop: 14 }]}>Kỹ năng cộng thêm</Text><Text style={s.bullet}>•  Kiến thức TypeScript cơ bản</Text><Text style={s.bullet}>•  Có kinh nghiệm viết kiểm thử hoặc tài liệu API</Text></Card>
    <Card><Text style={s.sectionTitle}>Kỹ năng cần có</Text><Text style={s.label}>Bắt buộc</Text><Text style={s.helper}>Nền tảng cần thiết để bắt đầu công việc</Text><View style={s.pills}>{skills.map((skill) => <Pressable key={skill} onPress={() => setSkills((current) => current.filter((item) => item !== skill))}><Tag tone="purple">{skill} ×</Tag></Pressable>)}</View><TextInput style={s.input} value={extraSkill} onChangeText={setExtraSkill} placeholder="⌕  Tìm trong danh mục kỹ năng..." placeholderTextColor={c.muted} onSubmitEditing={addSkill} /><Text style={[s.label, { marginTop: 14 }]}>Ưu tiên</Text><Text style={s.helper}>Có thêm sẽ giúp bạn làm việc thuận lợi hơn</Text><View style={s.pills}><Tag tone="purple">PostgreSQL ×</Tag><Tag tone="purple">TypeScript ×</Tag></View></Card>
    <Card><Text style={s.sectionTitle}>Quyền lợi</Text>{[{title:'Mentor đồng hành',body:'Review code và hướng dẫn kỹ thuật hằng tuần.'},{title:'Hỗ trợ thực tập',body:'4–6 triệu đồng/tháng, linh hoạt theo lịch học.'}].map((item) => <View key={item.title} style={s.benefit}><View style={s.benefitIcon}><CompanyIcon name={{ ios: 'graduationcap', android: 'school', web: 'school' }} size={15} /></View><View style={{ flex: 1 }}><Text style={s.label}>{item.title}</Text><Text style={s.helper}>{item.body}</Text></View><CompanyIcon name={{ ios: 'trash', android: 'delete', web: 'delete' }} size={14} color={c.muted} /></View>)}<ActionButton title="Thêm quyền lợi" onPress={() => Alert.alert('Thêm quyền lợi', 'Trường nhập quyền lợi sẽ được bổ sung sau.')} variant="soft" icon={{ ios: 'plus', android: 'add', web: 'add' }} /></Card>
    <Card><Text style={s.sectionTitle}>Lĩnh vực dự án phù hợp</Text><View style={s.pills}><Tag tone="purple">Ứng dụng web ×</Tag><Tag tone="purple">Sản phẩm doanh nghiệp ×</Tag></View><ActionButton title="Thêm lĩnh vực" onPress={() => Alert.alert('Lĩnh vực', 'Danh mục lĩnh vực sẽ được bổ sung sau.')} variant="outline" icon={{ ios: 'plus', android: 'add', web: 'add' }} /><Text style={s.helper}>Đề xuất mở rộng · Thể lĩnh vực có thể cấu hình, bổ sung cho từng ngành nghề.</Text></Card>
    <View style={s.submitRow}><ActionButton title="Lưu bản nháp" onPress={() => saveJob('Bản nháp')} variant="outline" icon={{ ios: 'tray.and.arrow.down', android: 'save', web: 'save' }} /><ActionButton title="Đăng bài tuyển dụng" onPress={() => saveJob('Đã đăng')} icon={{ ios: 'paperplane.fill', android: 'send', web: 'send' }} /></View>
  </PageScroll></CompanyPage>;
}

const s = StyleSheet.create({ nav: { flexDirection: 'row', alignItems: 'center', gap: 8 }, back: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFF' }, navTitle: { color: c.ink, fontSize: 13, fontWeight: '900' }, navSub: { color: c.muted, fontSize: 9, marginTop: 2 }, avatar: { width: 28, height: 28, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: c.purpleSoft }, avatarText: { color: c.purple, fontWeight: '900', fontSize: 10 }, jobPreview: { gap: 8 }, previewTop: { flexDirection: 'row', alignItems: 'center', gap: 8 }, logo: { width: 30, height: 30, borderRadius: 9, backgroundColor: c.purple, alignItems: 'center', justifyContent: 'center' }, logoText: { color: '#FFF', fontWeight: '900' }, company: { color: c.ink, fontWeight: '800', fontSize: 10 }, helper: { color: c.muted, fontSize: 9, lineHeight: 14 }, previewTitle: { color: c.ink, fontSize: 16, fontWeight: '900' }, previewSub: { color: c.muted, fontSize: 10 }, pills: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, alignItems: 'center' }, separator: { height: 1, backgroundColor: c.line }, previewDetail: { flexDirection: 'row', gap: 7, alignItems: 'center' }, sectionTitle: { color: c.ink, fontSize: 14, fontWeight: '900', marginBottom: 4 }, sectionSub: { color: c.muted, fontSize: 9, marginBottom: 5 }, field: { marginTop: 8, gap: 5 }, label: { color: c.ink, fontSize: 10, fontWeight: '700' }, input: { minHeight: 40, borderRadius: 10, borderWidth: 1, borderColor: c.line, backgroundColor: '#FFF', paddingHorizontal: 10, color: c.ink, fontSize: 10 }, textarea: { minHeight: 110, paddingTop: 10, lineHeight: 16 }, salaryRow: { flexDirection: 'row', gap: 8 }, bullet: { color: c.ink, fontSize: 10, lineHeight: 16, marginTop: 7 }, addSkillRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 8 }, purpleText: { color: c.purple, fontSize: 10, fontWeight: '800' }, benefit: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 8, borderBottomWidth: 1, borderColor: c.line }, benefitIcon: { width: 28, height: 28, borderRadius: 9, alignItems: 'center', justifyContent: 'center', backgroundColor: c.purpleSoft }, submitRow: { flexDirection: 'row', gap: 8 }, pill: { borderWidth: 1, borderColor: c.line, borderRadius: 20, paddingHorizontal: 10, paddingVertical: 7, backgroundColor: '#FFF' }, pillActive: { backgroundColor: c.purple, borderColor: c.purple }, pillText: { color: c.muted, fontSize: 9, fontWeight: '700' }, pillTextActive: { color: '#FFF' } });
