import { useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { ActionButton, Card, CompanyIcon, CompanyPage, companyColors as c, PageScroll, PageTitle, Tag } from '@/components/company/company-ui';
import { companyJobs } from '@/components/company/company-data';

const filters = ['Tất cả', 'Đã đăng', 'Bản nháp', 'Đã đóng', 'Hết hạn'];
const statusTone = { 'Đã đăng': 'green', 'Bản nháp': 'gray', 'Đã đóng': 'gray', 'Hết hạn': 'amber' } as const;

export default function CompanyJobs() {
  const [filter, setFilter] = useState('Tất cả');
  const [query, setQuery] = useState('');
  const visibleJobs = useMemo(() => companyJobs.filter((job) => (filter === 'Tất cả' || job.status === filter) && `${job.title} ${job.department}`.toLowerCase().includes(query.toLowerCase())), [filter, query]);
  return <CompanyPage><PageScroll>
    <View style={s.headingRow}><PageTitle title="Quản lý bài đăng" subtitle="Theo dõi các cơ hội và hồ sơ ứng tuyển." /><Pressable onPress={() => router.push('/(company)/create')} style={s.addButton}><CompanyIcon name={{ ios: 'plus', android: 'add', web: 'add' }} color="#FFF" /></Pressable></View>
    <View style={s.summary}><Text style={s.summaryTitle}>Bài đăng tuyển dụng</Text><Text style={s.summaryCopy}>Nexora Studio · 6 bài đăng · 40 hồ sơ</Text><View style={s.summaryTiles}>{[{n:'3',l:'Đang tuyển'}, {n:'1',l:'Bản nháp'}, {n:'1',l:'Sắp hết hạn'}].map((x) => <View style={s.summaryTile} key={x.l}><Text style={s.tileValue}>{x.n}</Text><Text style={s.tileLabel}>{x.l}</Text></View>)}</View></View>
    <View style={s.search}><CompanyIcon name={{ ios: 'magnifyingglass', android: 'search', web: 'search' }} color={c.muted} size={16} /><TextInput value={query} onChangeText={setQuery} placeholder="Tìm theo tiêu đề hoặc bộ phận..." placeholderTextColor={c.muted} style={s.searchInput} /></View>
    <View style={s.filters}>{filters.map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[s.filterChip, filter === item && s.filterActive]}><Text style={[s.filterText, filter === item && s.filterTextActive]}>{item}</Text></Pressable>)}</View>
    <Text style={s.count}>{visibleJobs.length} bài đăng</Text>
    {visibleJobs.map((job) => <Card key={job.id} style={s.jobCard}><View style={s.cardTitleRow}><Text style={s.jobTitle}>{job.title}</Text><Tag tone={statusTone[job.status]}>{job.status}</Tag></View><Text style={s.jobSubtitle}>{job.department} · {job.workplace} · {job.location}</Text><View style={s.metaGrid}><View><Text style={s.metaLabel}>Hạn ứng tuyển</Text><Text style={s.metaValue}>{job.deadline}</Text></View><View><Text style={s.metaLabel}>Ứng viên</Text><Text style={s.metaValue}>{job.applicants} hồ sơ</Text></View><View><Text style={s.metaLabel}>Cập nhật</Text><Text style={s.metaValue}>{job.updated}</Text></View></View><View style={s.buttons}>{job.applicants > 0 && <ActionButton title="Ứng viên" onPress={() => router.push('/(company)/applicants')} variant="outline" icon={{ ios: 'person.2', android: 'groups', web: 'groups' }} />}{job.status === 'Bản nháp' ? <ActionButton title="Tiếp tục sửa" onPress={() => router.push('/(company)/create')} icon={{ ios: 'pencil', android: 'edit', web: 'edit' }} /> : <><ActionButton title="Sửa" onPress={() => router.push('/(company)/create')} variant="outline" icon={{ ios: 'pencil', android: 'edit', web: 'edit' }} /><ActionButton title={job.status === 'Đã đăng' ? 'Đóng' : 'Xem'} onPress={() => Alert.alert(job.status === 'Đã đăng' ? 'Đóng bài đăng?' : 'Xem bài đăng', 'Thao tác sẽ được kết nối với dữ liệu thật sau.')} variant="outline" /></>}</View></Card>)}
  </PageScroll></CompanyPage>;
}

const s = StyleSheet.create({ headingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, addButton: { width: 40, height: 40, borderRadius: 12, backgroundColor: c.purple, alignItems: 'center', justifyContent: 'center' }, summary: { backgroundColor: c.purple, padding: 14, borderRadius: 17, gap: 5 }, summaryTitle: { color: '#FFF', fontSize: 18, fontWeight: '900' }, summaryCopy: { color: 'rgba(255,255,255,0.84)', fontSize: 10 }, summaryTiles: { flexDirection: 'row', gap: 7, marginTop: 8 }, summaryTile: { flex: 1, backgroundColor: 'rgba(255,255,255,0.17)', padding: 10, borderRadius: 11 }, tileValue: { color: '#FFF', fontSize: 18, fontWeight: '900' }, tileLabel: { color: 'rgba(255,255,255,0.84)', fontSize: 9, marginTop: 3 }, search: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#FFF', borderColor: c.line, borderWidth: 1, borderRadius: 12, minHeight: 43, paddingHorizontal: 11 }, searchInput: { flex: 1, fontSize: 11, color: c.ink, paddingVertical: 8 }, filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, filterChip: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 20, backgroundColor: '#FFF', borderWidth: 1, borderColor: c.line }, filterActive: { backgroundColor: c.purpleSoft, borderColor: c.purpleSoft }, filterText: { color: c.muted, fontSize: 9, fontWeight: '700' }, filterTextActive: { color: c.purple }, count: { color: c.muted, fontSize: 10 }, jobCard: { gap: 10 }, cardTitleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 7, justifyContent: 'space-between' }, jobTitle: { flex: 1, color: c.ink, fontSize: 12, fontWeight: '900' }, jobSubtitle: { color: c.muted, fontSize: 10, lineHeight: 15, marginTop: -5 }, metaGrid: { flexDirection: 'row', justifyContent: 'space-between', gap: 4, borderTopWidth: 1, borderColor: c.line, paddingTop: 10 }, metaLabel: { color: c.muted, fontSize: 9 }, metaValue: { color: c.ink, fontSize: 10, fontWeight: '800', marginTop: 4 }, buttons: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, });
