import { Alert, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { ActionButton, Card, CompanyIcon, CompanyPage, companyColors as c, PageScroll, PageTitle, SectionTitle, Tag, type CompanyIconName } from '@/components/company/company-ui';
import { companyJobs } from '@/components/company/company-data';

const contactItems: { icon: CompanyIconName; text: string }[] = [
  { icon: { ios: 'envelope', android: 'mail', web: 'mail' }, text: 'careers@nexora.example' },
  { icon: { ios: 'mappin.and.ellipse', android: 'location_on', web: 'location_on' }, text: '24 Nguyễn Bỉnh Khiêm, phường Sài Gòn, TP. Hồ Chí Minh' },
  { icon: { ios: 'phone', android: 'call', web: 'call' }, text: 'Số điện thoại: Chưa cập nhật' },
  { icon: { ios: 'link', android: 'link', web: 'link' }, text: 'nexora.example' },
];
const benefitItems: { icon: CompanyIconName; title: string; body: string }[] = [
  { icon: { ios: 'graduationcap', android: 'school', web: 'school' }, title: 'Có người đồng hành', body: 'Mentor hỗ trợ và phản hồi mỗi tuần.' },
  { icon: { ios: 'book', android: 'book', web: 'book' }, title: 'Học qua sản phẩm thật', body: 'Tham gia dự án, review code và chia sẻ kiến thức.' },
  { icon: { ios: 'cup.and.saucer', android: 'coffee', web: 'coffee' }, title: 'Môi trường cởi mở', body: 'Tôn trọng ý kiến, linh hoạt với lịch học.' },
  { icon: { ios: 'heart', android: 'favorite', web: 'favorite' }, title: 'Phát triển dài hạn', body: 'Cơ hội trở thành nhân sự chính thức sau kỳ thực tập.' },
];

export default function CompanyProfile() {
  const edit = () => Alert.alert('Chỉnh sửa hồ sơ', 'Chức năng chỉnh sửa hồ sơ công ty sẽ được kết nối sau.');
  return <CompanyPage><PageScroll>
    <PageTitle title="Hồ sơ công ty" subtitle="Giới thiệu Nexora Studio với cộng đồng sinh viên UniNet. Bạn có thể chỉnh sửa liên hệ, lĩnh vực, bao gồm email, địa chỉ và số điện thoại." />
    <View style={s.actions}><ActionButton style={{ flex: 1 }} title="Xem hồ sơ công khai" onPress={() => Alert.alert('Hồ sơ công khai', 'Bản xem trước hồ sơ công ty.')} variant="outline" icon={{ ios: 'arrow.up.right.square', android: 'open_in_new', web: 'open_in_new' }} /><ActionButton style={{ flex: 1 }} title="Chỉnh sửa hồ sơ" onPress={edit} icon={{ ios: 'pencil', android: 'edit', web: 'edit' }} /></View>
    <Card style={s.profileCard}>
      <View style={s.cover}><View style={s.coverBlockA} /><View style={s.coverBlockB} /><View style={s.coverWindow}><CompanyIcon name={{ ios: 'building.2.fill', android: 'business', web: 'business' }} size={34} color="#FFFFFF" /></View><View style={s.coverSun} /></View>
      <View style={s.companyTitleRow}><View style={s.companyLogo}><Text style={s.logoText}>N</Text></View><View style={s.companyTitle}><Text style={s.companyName}>Nexora Studio</Text><Tag tone="green">Hồ sơ công khai</Tag></View></View>
      <Text style={s.description}>Sản phẩm số tử tế. Cơ hội thật cho tài năng trẻ.</Text>
      <View style={s.chips}><Tag tone="gray">Công nghệ thông tin</Tag><Tag tone="gray">TP. Hồ Chí Minh</Tag><Tag tone="gray">51–100 thành viên</Tag></View>
    </Card>
    <Card><SectionTitle title="Về Nexora Studio" /><Text style={s.body}>Nexora Studio là đội ngũ thiết kế và phát triển sản phẩm số tại TP. Hồ Chí Minh. Chúng tôi xây dựng các nền tảng giúp doanh nghiệp vận hành nhanh hơn, từ trải nghiệm người dùng đến hệ thống dữ liệu.</Text><Text style={[s.body, { marginTop: 9 }]}>Chúng tôi chào đón sinh viên muốn học từ những bài toán thật. Bạn sẽ làm việc cùng người hướng dẫn, được chia sẻ ý tưởng và nhìn thấy đóng góp của mình trong sản phẩm. Kỹ năng, tinh thần học hỏi và sự chủ động là điểm bắt đầu cho cuộc trò chuyện.</Text><View style={s.chips}><Tag tone="purple">Sản phẩm số</Tag><Tag tone="purple">Thiết kế trải nghiệm</Tag><Tag tone="purple">Phát triển phần mềm</Tag></View></Card>
    <Card><SectionTitle title="Cơ hội đang mở" action="Quản lý bài đăng" onAction={() => router.push('/(company)/jobs')} /><Text style={s.helper}>Dành cho sinh viên và người mới tốt nghiệp</Text>{companyJobs.filter((job) => job.status === 'Đã đăng').map((job) => <View key={job.id} style={s.job}><View style={s.jobHead}><View style={s.jobIcon}><CompanyIcon name={{ ios: 'chevron.left.forwardslash.chevron.right', android: 'code', web: 'code' }} size={17} /></View><View style={{ flex: 1 }}><Text style={s.jobTitle}>{job.title}</Text><Text style={s.helper}>{job.department} · {job.workplace} · {job.location}</Text></View><Tag tone="green">Đã đăng</Tag></View><Text style={s.salary}>{job.salary}</Text></View>)}</Card>
    <Card style={s.notice}><CompanyIcon name={{ ios: 'checkmark.shield', android: 'verified_user', web: 'verified_user' }} color={c.blue} /><Text style={s.noticeText}>Trước khi công khai, website và đường dẫn trong hồ sơ được kiểm tra an toàn, đồng thời có thể cần kiểm duyệt. Việc này không ảnh hưởng xác minh hay duyệt tin.</Text></Card>
    <Card><SectionTitle title="Liên hệ công ty" /><View style={s.contactHead}><View style={s.avatar}><Text style={s.avatarText}>NS</Text></View><View><Text style={s.personName}>Nexora Studio</Text><Text style={s.helper}>Thông tin liên hệ doanh nghiệp</Text></View></View>{contactItems.map((item) => <View key={item.text} style={s.contactRow}><CompanyIcon name={item.icon} size={14} color={c.muted} /><Text style={s.contactText}>{item.text}</Text></View>)}<ActionButton title="Chỉnh sửa liên hệ" onPress={edit} variant="soft" icon={{ ios: 'pencil', android: 'edit', web: 'edit' }} /></Card>
    <Card><SectionTitle title="Điều bạn nhận được" />{benefitItems.map((item) => <View key={item.title} style={s.benefit}><View style={s.benefitIcon}><CompanyIcon name={item.icon} size={15} /></View><View style={{ flex: 1 }}><Text style={s.personName}>{item.title}</Text><Text style={s.helper}>{item.body}</Text></View></View>)}</Card>
  </PageScroll></CompanyPage>;
}

const s = StyleSheet.create({ actions: { flexDirection: 'row', gap: 8 }, profileCard: { padding: 0, overflow: 'hidden' }, cover: { height: 132, backgroundColor: '#DCE8E6', overflow: 'hidden', flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'center' }, coverBlockA: { width: '28%', height: 78, backgroundColor: '#A7C4BE', marginHorizontal: 2 }, coverBlockB: { width: '25%', height: 102, backgroundColor: '#8AAFA9', marginHorizontal: 2 }, coverWindow: { width: '30%', height: 117, borderTopLeftRadius: 18, borderTopRightRadius: 18, backgroundColor: '#5D8580', alignItems: 'center', justifyContent: 'center' }, coverSun: { position: 'absolute', top: 18, right: 25, width: 32, height: 32, borderRadius: 16, backgroundColor: '#F6DCA1' }, companyTitleRow: { flexDirection: 'row', gap: 10, paddingHorizontal: 14, marginTop: 12, alignItems: 'center' }, companyLogo: { width: 46, height: 46, borderRadius: 13, backgroundColor: c.purple, alignItems: 'center', justifyContent: 'center' }, logoText: { color: '#FFF', fontSize: 25, fontWeight: '900' }, companyTitle: { flex: 1, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 7 }, companyName: { color: c.ink, fontSize: 17, fontWeight: '900' }, description: { color: c.muted, fontSize: 11, lineHeight: 16, marginTop: 9, marginHorizontal: 14 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10, marginHorizontal: 14, marginBottom: 14 }, body: { color: c.ink, fontSize: 11, lineHeight: 18 }, helper: { color: c.muted, fontSize: 9, lineHeight: 14 }, job: { paddingTop: 12, marginTop: 11, borderTopWidth: 1, borderColor: c.line }, jobHead: { flexDirection: 'row', alignItems: 'center', gap: 8 }, jobIcon: { width: 31, height: 31, borderRadius: 9, backgroundColor: c.purpleSoft, alignItems: 'center', justifyContent: 'center' }, jobTitle: { color: c.ink, fontWeight: '800', fontSize: 10 }, salary: { color: c.purple, fontSize: 9, fontWeight: '700', marginTop: 7, marginLeft: 39 }, notice: { flexDirection: 'row', gap: 8, backgroundColor: '#F5F8FF' }, noticeText: { flex: 1, color: c.muted, fontSize: 9, lineHeight: 14 }, contactHead: { flexDirection: 'row', gap: 8, alignItems: 'center', paddingBottom: 8, borderBottomWidth: 1, borderColor: c.line }, avatar: { width: 29, height: 29, borderRadius: 15, backgroundColor: c.purpleSoft, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: c.purple, fontSize: 9, fontWeight: '900' }, personName: { color: c.ink, fontSize: 10, fontWeight: '800' }, contactRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, paddingVertical: 8 }, contactText: { flex: 1, color: c.ink, fontSize: 9, lineHeight: 14 }, benefit: { flexDirection: 'row', gap: 8, alignItems: 'center', paddingVertical: 7 }, benefitIcon: { width: 29, height: 29, borderRadius: 9, backgroundColor: c.purpleSoft, alignItems: 'center', justifyContent: 'center' } });
